services:
  db:
    image: postgres:16
    container_name: epm_trial_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: epm_trial
    ports:
      - "5434:5432"  # 左側を 5434 に変更
    volumes:
      - epm_trial_db:/var/lib/postgresql/data

volumes:
  epm_trial_db:
